INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12", "JufoLuokkaVanha", "JufoLuokkaUusi", "Alayksikko") VALUES ('10076', 2011, 'a1', 1, '1007626763', 2011, 'Special section on wireless mobile and multimedia networks', '"Mohapatra, Prasant; Ott, Jorg"', 2, 'pp. 921-921', null, null, '53925', '1', '528', 'Computer communications', '0140-3664', '34', '8', null, null, null, null, null, 'A1', '1', null, null, null, null, 'en', '9', null, null, null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2', 'H1');
INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12", "JufoLuokkaVanha", "JufoLuokkaUusi", "Alayksikko") VALUES ('10076', 2011, 'a2', 1, '1007626811', 2011, 'Spin-glass behavior of nanocrystalline multiferroic bismuth ferrite lead titanate', '"Tuboltsev, V.; Savin, A.; Sakamoto, W.; Hieno, A.; Yogo, T.; Raisanen, J."', 6, 'pp. 781-788', null, null, '60943', '3', '826', 'Journal of materials chemistry', '0959-9428', '21', '3', null, null, null, null, null, 'A1', '0', null, null, null, null, 'en', '9', null, 'http://dx."DOI".org/10.1039/c0jm02273j', null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2', 'H1');
INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12", "JufoLuokkaVanha", "JufoLuokkaUusi", "Alayksikko") VALUES ('10076', 2011, 'a3', 1, '1007629128', 2011, 'The non-birefringent limit of all linear, skewonless media and its unique light-cone structure', '"Bergamin, Luzi; Favaro, Alberto"', 2, '383-401', null, null, '51135', '1', '276', 'Annalen der Physik', '1521-3889', '523', '5', null, null, null, null, null, 'A1', '1', null, null, null, null, 'en', '9', null, 'http://dx."DOI".org/10.1002/andp.201000140', null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2', 'H1');
INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12", "JufoLuokkaVanha", "JufoLuokkaUusi", "Alayksikko") VALUES ('10076', 2011, 'a4', 1, '1007629263', 2011, 'Toolonlahden pelikenttä tayttyy.The game at Toolonlahti bay heats up.Keskuspusikko', 'Hernberg, Hella', 1, '73-75', null, null, '70117', '0', '246', 'Arkkitehti', '0783-3660', '108', '5', null, null, null, null, null, 'A1', '0', null, null, null, null, null, '9', null, null, null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2', 'H1');

--INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12") VALUES ('10076', 2011, 'a1', 1, '1007626763', 2011, 'Special section on wireless mobile and multimedia networks', '"Mohapatra, Prasant; Ott, Jorg"', 2, 'pp. 921-921', null, null, '53925', '1', '528', 'Computer communications', '0140-3664', '34', '8', null, null, null, null, null, 'A1', '1', null, null, null, null, 'en', '9', null, null, null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null);
--INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12") VALUES ('10076', 2011, 'a2', 1, '1007626811', 2011, 'Spin-glass behavior of nanocrystalline multiferroic bismuth ferrite lead titanate', '"Tuboltsev, V.; Savin, A.; Sakamoto, W.; Hieno, A.; Yogo, T.; Raisanen, J."', 6, 'pp. 781-788', null, null, '60943', '3', '826', 'Journal of materials chemistry', '0959-9428', '21', '3', null, null, null, null, null, 'A1', '0', null, null, null, null, 'en', '9', null, 'http://dx."DOI".org/10.1039/c0jm02273j', null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null);
--INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12") VALUES ('10076', 2011, 'a3', 1, '1007629128', 2011, 'The non-birefringent limit of all linear, skewonless media and its unique light-cone structure', '"Bergamin, Luzi; Favaro, Alberto"', 2, '383-401', null, null, '51135', '1', '276', 'Annalen der Physik', '1521-3889', '523', '5', null, null, null, null, null, 'A1', '1', null, null, null, null, 'en', '9', null, 'http://dx."DOI".org/10.1002/andp.201000140', null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null);
--INSERT INTO "TK_Julkaisut" ("OrganisaatioTunnus", "IlmoitusVuosi", "JulkaisunTunnus", "JulkaisunTilaKoodi", "JulkaisunOrgTunnus", "JulkaisuVuosi", "JulkaisunNimi", "TekijatiedotTeksti", "TekijoidenLkm", "SivunumeroTeksti", "Artikkelinumero", "ISBN", "JufoTunnus", "JufoLuokkaKoodi", "JulkaisumaaKoodi", "LehdenNimi", "ISSN", "VolyymiTeksti", "LehdenNumeroTeksti", "KonferenssinNimi", "KustantajanNimi", "KustannuspaikkaTeksti", "EmojulkaisunNimi", "EmojulkaisunToimittajatTeksti", "JulkaisutyyppiKoodi", "YhteisjulkaisuKVKytkin", "YhteisjulkaisuSHPKytkin", "YhteisjulkaisuTutkimuslaitosKytkin", "YhteisjulkaisuMuuKytkin", "JulkaisunKansainvalisyysKytkin", "JulkaisunKieliKoodi", "AvoinSaatavuusKoodi", "EVOjulkaisuKytkin", "DOI", "PysyvaOsoiteTeksti", "LahdetietokannanTunnus", "Lataus_ID", "Yhteisjulkaisu_Id", "RinnakkaistallenettuKytkin", "YhteisjulkaisunTunnus", "JuuliOsoiteTeksti", "YhteisjulkaisuYritysKytkin", "Jufo_ID", "OrgSektori", "kasvatusalat_1", "taiteet_ja_kulttuurialat_2", "humanistiset_alat_3", "yhteiskunnalliset_alat_4", "kauppa_hallinto_ja_oikeustieteet_5", "luonnontieteet_6", "tietojenkasittely_ja_tietoliikenne_7", "tekniikan_alat_8", "maa_ja_metsatalousalat_9", "laaketieteet_10", "terveys_ja_hyvinvointialat_11", "palvelualat_12") VALUES ('10076', 2011, 'a4', 1, '1007629263', 2011, 'Töölönlahden pelikenttä täyttyy.The game at Töölönlahti bay heats up.Keskuspusikko', 'Hernberg, Hella', 1, '73-75', null, null, '70117', '0', '246', 'Arkkitehti', '0783-3660', '108', '5', null, null, null, null, null, 'A1', '0', null, null, null, null, null, '9', null, null, null, null, 'CSV20160529', '0', null, null, null, null, null,0, null, null, null, null, null, null, null, null, null, null, null, null);


INSERT INTO "TK_Hanke" ("JulkaisunTunnus", "Hankenumero", "RahoittajaOrg", "Lataus_ID") VALUES ('a1', '123abc', 'xyz', '1');
INSERT INTO "TK_Hanke" ("JulkaisunTunnus", "Hankenumero", "RahoittajaOrg", "Lataus_ID") VALUES ('a1', '124abc', 'xyz1', '1');
INSERT INTO "TK_Hanke" ("JulkaisunTunnus", "Hankenumero", "RahoittajaOrg", "Lataus_ID") VALUES ('a2', '12ab', 'xyz', '1');
INSERT INTO "TK_Hanke" ("JulkaisunTunnus", "Hankenumero", "RahoittajaOrg", "Lataus_ID") VALUES ('a2', '13ab', 'xyz1', '2');

INSERT INTO "TK_Avainsanat" ("JulkaisunTunnus", "Avainsana", "Lataus_ID") VALUES ('a1', 'avain1', '1');
INSERT INTO "TK_Avainsanat" ("JulkaisunTunnus", "Avainsana", "Lataus_ID") VALUES ('a1', 'avain2', '1');
INSERT INTO "TK_Avainsanat" ("JulkaisunTunnus", "Avainsana", "Lataus_ID") VALUES ('a1', 'avain3', '1');
INSERT INTO "TK_Avainsanat" ("JulkaisunTunnus", "Avainsana", "Lataus_ID") VALUES ('a2', 'avain1', '2');

INSERT INTO "TK_ISBN" ("JulkaisunTunnus", "ISBN", "Lataus_ID") VALUES ('a1', 'isbn1', '1');

INSERT INTO "TK_ISSN" ("JulkaisunTunnus", "ISSN", "Lataus_ID") VALUES ('a1', 'issn1', '1');

INSERT INTO "TK_Koulutusalat" ("JulkaisunTunnus", "Koulutusala", "JNro", "Lataus_ID") VALUES ('a1', 11, 1, '1');
INSERT INTO "TK_Koulutusalat" ("JulkaisunTunnus", "Koulutusala", "JNro", "Lataus_ID") VALUES ('a1', 22, 2, '1');

INSERT INTO "TK_OrgYksikko" ("JulkaisunTunnus", "OrganisaatioTunnus", "julkaisu_yksikko", "tekija_yksikko", "Lataus_ID") VALUES ('a1', 'org1', 'julkyk1', 'tekyk1', '1');

INSERT INTO "TK_Tekijat" ("JulkaisunTunnus", "Etunimet", "Sukunimi", "ORCID", "Yksikko", "Lataus_ID", "Rooli") VALUES ('a1', 'Matti Teppo', 'Meikalainen', 'orcid123', 'yksikko1', '1', null);

INSERT INTO "TK_Tieteenalat" ("JulkaisunTunnus", "Tieteenala", "JNro", "Lataus_ID") VALUES ('a1', 111, 1, '1');

INSERT INTO "TK_Taiteenalat" ("JulkaisunTunnus", "Taiteenala", "JNro", "Lataus_ID") VALUES ('a1', 2, 1, '1');
